close all;
fsz = 22;
ax = feature{1,30}(:,1);
ay = feature{1,30}(:,2);
plot(ax,ay,'bo-');
bx = feature{5,30}(:,1);
by = feature{5,30}(:,2);
hold on;
plot(bx,by,'ro-');
x = min(bx):1:max(bx);
y = interp1(ax, ay, x, 'spline', 'extrap');
xlabel('½Ø¾à','fontsize',fsz);
ylabel('Ð±ÂÊ','fontsize',fsz);
legend({'a_{train}','a_{test}'},'FontSize',fsz);
hold on;
plot(x,y,'m-');
legend({'a_{train}','a_{test}','f(x)'},'FontSize',fsz);
plot(bx,interp1(ax, ay, bx, 'spline', 'extrap'), 'mo');
legend({'a_{train}','a_{test}','f(x)','a''_{train}'},'FontSize',fsz);